# Generated by Django 5.0.3 on 2024-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_githubrepository"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="knowledge",
            field=models.TextField(blank=True, null=True),
        ),
    ]
