# Generated by Django 5.0.3 on 2024-09-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_githubrepository_knowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepository",
            name="skills_file_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
