# Generated by Django 5.0.2 on 2024-03-04 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(max_length=2000)),
                ('html_url', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.IntegerField(unique=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('access_tokens_url', models.URLField(max_length=2000)),
                ('repositories_url', models.URLField(max_length=2000)),
                ('app_id', models.IntegerField()),
                ('target_id', models.IntegerField()),
                ('target_type', models.CharField(max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='accounts.githubaccount')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.IntegerField(unique=True)),
                ('node_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='accounts.githubappinstallation')),
            ],
        ),
    ]
