apiVersion: batch/v1
kind: CronJob
metadata:
  name: pr-pilot-collect-skills-hub-data
spec:
  schedule: "0 * * * *"  # Every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collect-skills-hub-data
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: Always
            resources:
              limits:
                memory: "512Mi"
                cpu: "250m"
              requests:
                memory: "512Mi"
                cpu: "250m"
            command: ["python", "manage.py", "collect_skills_hub_data"]
            env:
            - name: GITHUB_APP_PRIVATE_KEY_PATH
              value: "/etc/ssl/certs/github_private_key.pem"
            - name: REDIS_HOST
              value: "pr-pilot-redis-master.default.svc.cluster.local"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pr-pilot-db-postgresql
                  key: postgres-password
            envFrom:
            - secretRef:
                name: pr-pilot-secret
            volumeMounts:
            - name: pem-volume
              mountPath: /etc/ssl/certs/github_private_key.pem
              subPath: github_app_private_key.pem
          restartPolicy: OnFailure
          volumes:
          - name: pem-volume
            secret:
              secretName: pr-pilot-private-key
