# Generated by Django 5.0.3 on 2024-09-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webhooks", "0003_githubrepository_knowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("result", models.TextField()),
                (
                    "github_repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="webhooks.githubrepository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PilotSkillArgument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arguments",
                        to="hub.pilotskill",
                    ),
                ),
            ],
        ),
    ]
