# Generated by Django 5.0.3 on 2024-09-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pilotskill",
            name="category",
            field=models.CharField(
                blank=True, default="Other", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="pilotskill",
            name="programming_languages",
            field=models.ManyToManyField(
                related_name="skills", to="hub.programminglanguage"
            ),
        ),
        migrations.AddField(
            model_name="pilotskill",
            name="tags",
            field=models.ManyToManyField(related_name="skills", to="hub.tag"),
        ),
    ]
