# Generated by Django 5.0.3 on 2024-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_programminglanguage_tag_pilotskill_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingFramework",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pilotskill",
            name="programming_frameworks",
            field=models.ManyToManyField(
                related_name="skills", to="hub.programmingframework"
            ),
        ),
    ]
