# Generated by Django 5.0.3 on 2024-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_programmingframework_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilotskill",
            name="fa_icon_classes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
