# Generated by Django 5.0.3 on 2024-07-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0017_alter_task_installation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="gpt_model",
            field=models.CharField(
                blank=True, default="gpt-4o", max_length=200, null=True
            ),
        ),
    ]
